In [1]:
import pandas as pd

In [7]:
residencial = pd.read_csv('alquiler_residencial.csv')
residencial.head(30)

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
5,5,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
6,6,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
7,7,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
8,8,Departamento,Pachacámac,1,0,0,36,1200.0,NaN,NaN
9,9,Departamento,Mi Perú,2,1,0,70,1500.0,642.0,74.0
10,10,Departamento,San Borja,3,1,1,90,1500.0,455.0,14.0
11,11,Departamento,San Borja,1,0,1,40,2000.0,561.0,50.0
12,12,Habitación,San Borja,1,0,0,27,1800.0,501.0,NaN
13,13,Departamento,San Borja,4,3,1,243,13000.0,2000.0,803.0
14,14,Edificio completo,Chorrillos,0,0,0,536,28000.0,NaN,3563.0
15,15,Flat,Chorrillos,3,1,1,80,3800.0,1040.0,NaN
16,16,Casa en condominio,San Luis,3,1,1,115,2000.0,NaN,NaN
17,17,Departamento,Callao,3,0,0,54,950.0,300.0,28.0
18,18,Departamento,Ate,2,1,1,67,1700.0,589.0,147.0
19,19,Departamento,San Miguel,2,1,0,110,1900.0,700.0,138.0
20,20,Casa en condominio,Ate,4,3,2,466,7500.0,2695.0,NaN
21,21,Departamento,Santa Rosa,3,1,0,68,1000.0,670.0,NaN
22,22,Departamento,San Miguel,2,1,0,78,2000.0,700.0,NaN
23,23,Flat,Rímac,1,0,0,56,4500.0,1900.0,1500.0
24,24,Departamento,Comas,3,1,1,125,7000.0,2100.0,463.0
25,25,Departamento,San Miguel,1,0,0,48,750.0,772.0,25.0
26,26,Departamento,Ate,3,3,1,175,4200.0,1500.0,500.0
27,27,Casa,Lince,4,1,2,400,12000.0,NaN,NaN
28,28,Departamento,Chorrillos,2,1,0,76,2500.0,740.0,NaN
29,29,Departamento,San Borja,3,1,2,378,10000.0,2150.0,700.0

In [8]:
list(residencial['Tipo'].drop_duplicates())

['Habitación',
 'Casa',
 'Departamento',
 'Casa en condominio',
 'Edificio completo',
 'Flat',
 'Casa de villa',
 'Cochera',
 'Loft']

In [9]:
sel_depart = residencial['Tipo'] == 'Departamento'
cant_dept = residencial[sel_depart].shape[0]
cant_dept

19532

In [11]:
sel_chc = (residencial['Tipo']== 'Casa')|(residencial['Tipo']== 'Habitación')|(residencial['Tipo']== 'Cochera')
cant_chc = residencial[sel_chc].shape[0]
cant_chc

1885

In [13]:
sel_habxprecio = (residencial['Cuartos']>= 4) & (residencial['Valor']<=  2000)
cant_habxprecio = residencial[sel_habxprecio].shape[0]
cant_habxprecio

61

In [15]:
sel_areas = (residencial['Area']>= 60) & (residencial['Area']<=  100)
cant_areas = residencial[sel_areas].shape[0]
cant_areas

8992

In [16]:
print(f'La cantidad de departamentos encontrados es de {cant_dept}')
print(f'La cantidad de casas, habitaciones y cocheras encontradps es de {cant_chc}')
print(f'La cantidad de casas de 4 o más habitaciones que cuestan menos de 2000 es {cant_habxprecio}')
print(f'La cantidad de vivendas con un area entre 60 y 100 mts cuadrados es de {cant_areas}')

La cantidad de departamentos encontrados es de 19532
La cantidad de casas, habitaciones y cocheras encontradps es de 1885
La cantidad de casas de 4 o más habitaciones que cuestan menos de 2000 es 61
La cantidad de vivendas con un area entre 60 y 100 mts cuadrados es de 8992